### ISSUE TITLE
how do you dump the bootrom

### ISSUE THREAD

**Issue by JiaDuo** [qais744/LPC-ROP#2]
how do you dump the bootrom？ it can be read directly？

I try to read stm32 bootrom but failed！

please

**Comment by qaistem1** [comment]
Hi!

So basically you have to look where the ROM resides, from which address to which address, normally you can find this in the memory mapping documentation, and then flash a code that looks like this into the device:
`
for(Addr=(unsigned char *)0x1FFF0000;Addr&lt;=(unsigned char *)0x1FFFBFFF;Addr++)	
{		
printf("%02X",*Addr);	
}
`

This repo has a code for dumping STM32F401RE bootloader:
[https://github.com/qais744/EmbeddedSoftware](https://github.com/qais744/EmbeddedSoftware)

**Comment by JiaDuo** [comment]
thanks , I got it .
